catalog/urls.py
from django.urls import path
from . import views


app_name = 'Catalog'
urlpatterns = [
    # path('', views.catalog_page, name='catalog_page'),
    # path('product/<int:category_id>/', views.product_page, name='product_page'),
    # path('upload_category/', views.upload_category, name='upload_category'),
    # path('update_category/<int:category_id>', views.update_category, name='update_category'),
    # path('delete_category/<int:category_id>', views.delete_category, name='delete_category'),
    # path('upload_product/', views.upload_product, name='upload_product'),
    # path('update_product/<int:product_id>', views.update_book, name='update_product'),
    # path('delete_product/<int:product_id>', views.delete_book, name='delete_product'),

    path('', views.homepage, name='homepage'),
    path('Category', views.CategoryListView.as_view(), name='catalog_page'),
    path('upload_category/', views.CategoryUploadView.as_view(), name='upload_category'),
    path('update_category/<int:pk>', views.CategoryUpdateView.as_view(), name='update_category'),
    path('delete_category/<int:pk>', views.CategoryDeleteView.as_view(), name='delete_category'),
    path('book/<int:pk>/', views.CategoryDetailView.as_view(), name='book_page'),         # Category.id
    path('upload_book/', views.BookUploadView.as_view(), name='upload_book'),
    path('update_book/<int:pk>', views.BookUpdateView.as_view(), name='update_book'),
    path('delete_book/<int:pk>', views.BookDeleteView.as_view(), name='delete_book'),
    path('borrowed_book/', views.LoanedBooksByUserView.as_view(), name='borrowed_book'),
]

library_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('uploadimage/', include('uploadimage.urls')),
    path('uploadfile/', include('uploadfile.urls')),
    path('sendmail/', include('sendmail.urls')),
    path('Catalog/', include('Catalog.urls')),
    path('blog/', include('blog.urls')),
    path('User/', include('User.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#DataFlair
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import homepage, SignUpView, permission_request

app_name = 'User'

urlpatterns = [
    path("", homepage, name="homepage"),
    path('signup/', SignUpView.as_view(), name='signup'),
    path("permission/<int:user_id>/", permission_request, name="permission"),
    # path("", views.homepage, name="homepage"),
    # path("login/", views.login_request, name="login"),
    # path("register/", views.register_request, name="register"),
    # path("logout/", views.logout_request, name="logout"),

]

catalog/models.py
from django.db import models
import uuid     # Required for unique book instances
from datetime import date
from User.models import MyUser
import base64
from io import BytesIO
from PIL import Image
# Create your models here.


class Category(models.Model):
    """Model representing a book category."""
    name = models.CharField(max_length=200, null=True, help_text='Enter a book category (e.g. Science Fiction)')
    picture = models.ImageField(blank=True, upload_to='Catalog/Category/images')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


    @property
    def image_url(self):
        try:
            url = self.picture.url
        except:
            url = ''
        return url


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    category = models.ManyToManyField(Category, help_text='Select a category for this book')
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    picture = models.ImageField(blank=True, upload_to='Catalog/Product/images')
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    @property
    def image_url(self):
        try:
            url = self.picture.url
        except:
            url = ''
        return url


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(MyUser, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back', 'status']

    def __str__(self):
        return f'{self.id} ({self.book.title})'


@property
def is_overdue(self):
    return bool(self.due_back and date.today() > self.due_back)



# class ProductInstance(models.Model):
#     """Model representing a specific copy of a product (i.e. that can be borrowed from the library)."""
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4,
#                           help_text='Unique ID for this particular book across whole library')
#     # RESTRICT: ensure Product can't be delete
#     product = models.ForeignKey(Product, on_delete=models.RESTRICT, null=True)
#     borrower = models.ForeignKey(MyUser, on_delete=models.SET_NULL, null=True, blank=True)
#     due_back = models.DateField(null=True, blank=True)
#
#     LOAN_STATUS = (
#         ('m', 'Maintenance'),
#         ('o', 'On loan'),
#         ('a', 'Available'),
#         ('r', 'Reserved'),
#     )
#
#     status = models.CharField(
#         max_length=1,
#         choices=LOAN_STATUS,
#         blank=True,
#         default='m',
#         help_text='Book availability',
#     )
#
#     class Meta:
#         ordering = ['due_back']
#
#     def __str__(self):
#         """String for representing the Model object."""
#         return f'{self.id} ({self.product.name})'
#
#     @property
#     def is_overdue(self):
#         """Determines if the product is overdue based on due date and current date."""
#         return bool(self.due_back and date.today() > self.due_back)

# class Work(models.Model):
#     category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE)
#     sales = models.IntegerField(null=True)

# class Category(models.Model):
#     type = models.CharField(max_length=200)
#     picture = models.ImageField(blank=True, upload_to='Catalog/Category/images')
#
#     class Meta:
#         ordering = ['type']
#
#     def __str__(self):
#         return self.type
#
#     @property
#     def image_url(self):
#         try:
#             url = self.picture.url
#         except:
#             url = ''
#         return url

# class Product(models.Model):
#     type = models.ManyToManyField(Category)
#     name = models.CharField(max_length=200)
#     picture = models.ImageField(blank=True, upload_to='Catalog/Product/images')
#     pub_date = models.DateTimeField('date published')
#     author = models.CharField(max_length=30, null=True)
#     price = models.IntegerField(null=True)
#
#     class Meta:
#         ordering = ['name', 'price']
#
#     def __str__(self):
#         return self.name
#
#     @property
#     def image_url(self):
#         try:
#             url = self.picture.url
#         except:
#             url = ''
#         return url

catalog/forms.py
from django import forms
from .models import Category, Book, BookInstance, Author
from django.forms.utils import ErrorList
from django.utils.safestring import mark_safe


class ErrorListMsg(ErrorList):
    def __unicode__(self):
        return self.as_msg()

    def as_msg(self):
        if not self:
            return u''
        return mark_safe(u'\n'.join([u'<span class="red">%s</span>' % e for e in self]))


class MyBaseModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs_new = {'error_class': ErrorListMsg}
        kwargs_new.update(kwargs)
        super(MyBaseModelForm, self).__init__(*args, **kwargs_new)


class CategoryCreate(MyBaseModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class BookCreate(MyBaseModelForm):
    class Meta:
        model = Book
        fields = '__all__'


class BookInstanceCreate(MyBaseModelForm):
    class Meta:
        model = BookInstance
        fields = '__all__'


class AuthorCreate(MyBaseModelForm):
    class Meta:
        model = Author
        fields = '__all__'


# class DivErrorList(ErrorList):
#     def __unicode__(self):
#         return self.as_divs()
#
#     def as_divs(self):
#         if not self: return u''
#         return u'<div class="errorlist">%s</div>' % ''.join([u'<div class="error">%s</div>' % e for e in self])

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
# from django.http import HttpResponse
# from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy, reverse
from .models import Category, Book, BookInstance, Author
from .forms import CategoryCreate, BookCreate, BookInstanceCreate, AuthorCreate
from django.core.paginator import Paginator
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# error_class=ErrorListMsg


def homepage(request):
    """View function for home page of site."""

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'Catalog/index.html', context=context)


class CategoryListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    # Redirect to setting.LOGIN_URL in default
    # redirect_field_name = reverse_lazy('Catalog:catalog_page')
    permission_required = 'Catalog.view_category'
    model = Category
    paginate_by = 2
    context_object_name = 'list_category'
    template_name = 'Catalog/list_category.html'


class CategoryDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    permission_required = ('Catalog.view_category', 'Catalog.view_product')
    model = Category
    paginate_by = 1
    context_object_name = 'detail_category'
    template_name = 'Catalog/detail_category.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        category = self.object
        book_list = category.book_set.all()
        p = Paginator(book_list, self.paginate_by)
        page = self.request.GET.get('page')
        book_per_page = p.get_page(page)
        context['book_per_page'] = book_per_page
        return context


class CategoryUploadView(generic.CreateView):
    model = Category
    form_class = CategoryCreate
    template_name = 'Catalog/upload_category.html'
    success_url = reverse_lazy('Catalog:homepage')


class CategoryUpdateView(generic.UpdateView):
    model = Category
    form_class = CategoryCreate
    template_name = 'Catalog/update_category.html'
    success_url = reverse_lazy('Catalog:catalog_page')


class CategoryDeleteView(generic.DeleteView):
    model = Category
    template_name = 'Catalog/category_confirm_delete.html'
    success_url = reverse_lazy('Catalog:catalog_page')


class BookUploadView(CategoryUploadView):
    model = Book
    form_class = BookCreate

    # def get_success_url(self):
    #     # category = get_object_or_404(Category, pk=self.request.POST['pk'])
    #
    #     return reverse('Catalog:product_page', kwargs={'pk': self.request.POST['pk']})


class BookUpdateView(CategoryUpdateView):
    model = Book
    form_class = BookCreate


class BookDeleteView(CategoryDeleteView):
    model = Book


class LoanedBooksByUserView(LoginRequiredMixin, generic.ListView):

    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 2

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )

# @login_required(redirect_field_name=None)
# @permission_required('Catalog.view_category')
# def catalog_page(request):
#     category_list = Category.objects.all()
#     p = Paginator(category_list, 2)
#     page = request.GET.get('page')
#     category_per_page = p.get_page(page)
#     return render(request, 'Catalog/library.html',
#                   {'category_list': category_list, 'category_per_page': category_per_page})
#
#
# def upload_category(request):
#     if request.method == 'POST':
#         upload_form = CategoryCreate(request.POST, request.FILES)
#         if upload_form.is_valid():
#             upload_form.save()
#             return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))
#         else:
#             return HttpResponse("""your form is wrong, reload on <a href = "{% url 'Catalog:catalog_page' %}">reload</a>""") # fix
#     else:
#         upload_form = CategoryCreate()
#         return render(request, 'Catalog/upload_form.html', {'upload_form': upload_form})
#
#
# def update_category(request, category_id):
#     category_id = int(category_id)
#     try:
#         book = Category.objects.get(pk=category_id)
#     except Category.DoesNotExist:
#         return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))
#     category_form = CategoryCreate(request.POST, request.FILES, instance=book)
#     if category_form.is_valid():
#         category_form.save()
#         return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))
#     return render(request, 'Catalog/upload_form.html', {'upload_form': category_form})
#
#
# def delete_category(request, category_id):
#     category_id = int(category_id)
#     try:
#         category = Category.objects.get(id=category_id)
#     except Category.DoesNotExist:
#         return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))
#     category.delete()
#     return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))
#
#
# def product_page(request, category_id):
#     category = get_object_or_404(Category, pk=int(category_id))
#     product_list = category.product_set.all()
#     p = Paginator(product_list, 2)
#     page = request.GET.get('page')
#     product_per_page = p.get_page(page)
#     return render(request, 'Catalog/shelf.html',
#                   {'category': category, 'product_per_page': product_per_page})
#
#
# def upload_product(request):
#     if request.method == 'POST':
#         upload_form = ProductCreate(request.POST, request.FILES)
#         if upload_form.is_valid():
#             upload_form.save()
#             return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))
#         else:
#             return HttpResponse("""your form is wrong, reload on <a href = "{% url 'Catalog:catalog_page' %}">reload</a>""") # fix
#     else:
#         upload_form = ProductCreate()
#         return render(request, 'Catalog/upload_form.html', {'upload_form': upload_form})
#
#
# def update_book(request, product_id):
#     product_id = int(product_id)
#     try:
#         book = Product.objects.get(pk=product_id)
#     except Product.DoesNotExist:
#         return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))
#     product_form = ProductCreate(request.POST or None, instance=book)
#     if product_form.is_valid():
#         product_form.save()
#         return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))
#     return render(request, 'Catalog/upload_form.html', {'upload_form': product_form})
#
#
# def delete_book(request, product_id):
#     product_id = int(product_id)
#     try:
#         book = Product.objects.get(id=product_id)
#     except Product.DoesNotExist:
#         return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))
#     book.delete()
#     return HttpResponseRedirect(reverse_lazy('Catalog:catalog_page'))

catalog/templates/Catalog/bookinstance_list_borrowed_user.html
<h1>Borrowed books</h1>
    {% if bookinstance_list %}
    <ul>

      {% for bookInstance in bookinstance_list %}
      <li>
        {{ bookInstance.book.title }} ({{ bookInstance.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
    <a href="{% url 'Catalog:homepage' %}">Back to the homepage</a>

catalog/templates/Catalog/category_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
<p><a href="{% url 'Catalog:catalog_page' %}">Back</a></p>

catalog/templates/Catalog/detail_category.html
<html>
<h1> This list of {{detail_category.type}} </h1>
    <h2><a href="{% url 'Catalog:upload_book' %}">Upload Books</a></h2>
        <ul>
        {% for book in book_per_page %}
            <li>
                <h3><em>title of book:</em> {{book.title}}</h3>
                <p><em>Author:</em> {{book.author}}</p>
                <p><img src="{{book.picture.url }}"  width="400" height="500"></p>
                <p><em>Summary:</em> {{book.summary}}</p>
                <p>
                    <a href="{% url 'Catalog:update_book' book.id%}">edit</a>
                    <a href="{% url 'Catalog:delete_book' book.id%}">delete</a>
                </p>
            </li>
             <h3>Copies</h3>
                {% if book.bookinstance_set.all %}
                    {% for copy in book.bookinstance_set.all %}
                      <p>
                          <strong> {{ copy.get_status_display }} </strong>
                      </p>
                      {% if copy.status != 'a' %}
                        <p><em>Due to be returned:</em> {{ copy.due_back }}</p>
                      {% endif %}
                      <p><em>Imprint:</em> {{ copy.imprint }}</p>
                      <p><em>Id:</em> {{ copy.id }}</p>
                    {% endfor %}
                {% else %}
                    <p> No copies </p>
                {% endif %}
        {% endfor %}
        </ul>




    <p>Go <a href="{% url 'Catalog:catalog_page' %}">back</a></p>
    <p><a href="{% url 'logout' %}">Logout</a></p>
<hr><br/><br/>
        {% if book_per_page.has_previous %}
            <a href="{{ request.path }}?page=1"> &laquo First</a>
            <a href="{{ request.path }}?page={{ book_per_page.previous_page_number }}">previous</a>
        {% endif %}
        Page {{ book_per_page.number }} of {{ book_per_page.paginator.num_pages }}
        {% if book_per_page.has_next %}
            <a href="{{ request.path }}?page={{ book_per_page.next_page_number }}">next</a>
            <a href="{{ request.path }}?page={{book_per_page.paginator.num_pages}}">Last &raquo</a>
        {% endif %}

</html>

catalog/templates/Catalog/index.html
<h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><a href="{% url 'Catalog:catalog_page' %}"><strong>Books:</strong></a> {{ num_books }}</li>
    <li><a href="{% url 'Catalog:catalog_page' %}"><strong>Copies:</strong></a> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>
  <a href="{% url 'Catalog:borrowed_book' %}">See your borrowed book</a>

catalog/templates/Catalog/library.html
<html>
{% load static %}
<img src="{% static 'Catalog/images/Logo.jpg' %}" width="300" height="200" >
<h1> This is list of Category </h1>
    <h2><a href="{% url 'Catalog:upload_category' %}">Upload Category</a></h2>
        {% if category_list %}
        <p>
            <ul>
                {%for category in category_per_page %}
                    <li>
                        <p>Type of book: <a href ="{% url 'Catalog:product_page' category.id %}"> {{category.type}} </a> </p>
                        <img src="{{category.image_url }}"  width="400" height="500">
                        <p>
                            <a href="{% url 'Catalog:update_category' category.id%}">edit</a>
                            <a href="{% url 'Catalog:delete_category' category.id%}">delete</a>
                        </p>
                    </li>
                {% endfor %}
            </ul>
        </p>
        {% else %}
        <p> No type of category are available </p>
        {% endif %}
<hr><br/><br/>
        {% if category_per_page.has_previous %}
            <a href="?page=1"> &laquo First</a>
            <a href="?page={{category_per_page.previous_page_number}}">Previous</a>
        {% endif %}

        Page {{category_per_page.number}} of {{category_per_page.paginator.num_pages}}

        {% if category_per_page.has_next %}
            <a href="?page={{category_per_page.next_page_number}}">Next</a>
            <a href="?page={{category_per_page.paginator.num_pages}}">Last &raquo</a>
        {% endif %}

</html>

catalog/templates/Catalog/list_category.html
<html>
{% load static %}
<img src="{% static 'Catalog/images/Logo.jpg' %}" width="300" height="200" >
<h1> This is list of Category </h1>
    <h2><a href="{% url 'Catalog:upload_category' %}">Upload Category</a></h2>
        {% if list_category %}
        <p>
            <ul>
                {%for category in list_category %}
                    <li>
                        <p>Name of category: <a href ="{% url 'Catalog:book_page' category.id %}"> {{category.name}} </a> </p>
                        <img src="{{category.image_url }}"  width="400" height="500">
                        <p>Thumbnail: {{category.thumbnail}}</p>
                        <p>
                            <a href="{% url 'Catalog:update_category' category.id %}">edit</a>
                            <a href="{% url 'Catalog:delete_category' category.id %}">delete</a>
                        </p>
                    </li>
                {% endfor %}
            </ul>
        </p>
        {% else %}
        <p> No type of category are available </p>
        {% endif %}
    <p><a href="{% url 'logout' %}">Logout</a></p>
    <p><a href="{% url 'Catalog:homepage' %}">Back to the homepage</a></p>
<hr><br/><br/>
     {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page=1"> &laquo First</a>
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            <a href="{{ request.path }}?page={{page_obj.paginator.num_pages}}">Last &raquo</a>
        {% endif %}
    {% endif %}
</html>

catalog/templates/Catalog/shelf.html
<html>
<h1> This list of {{category.type}} </h1>
    <h2><a href="{% url 'Catalog:upload_product' %}">Upload Books</a></h2>
        <ul>
        {% for product in product_per_page %}
            <li>
                <h3><em>Name of book:</em> {{product.name}}</h3>
                <p><em>Public date:</em> {{product.pub_date}}</p>
                <p><em>Author:</em> {{product.author}}</p>
                <p><em>Price:</em> {{product.price}}</p>
                <p><img src="{{product.picture.url }}"  width="400" height="500"></p>
                <p>
                    <a href="{% url 'Catalog:update_product' product.id%}">edit</a>
                    <a href="{% url 'Catalog:delete_product' product.id%}">delete</a>
                </p>

            </li>
        {% endfor %}
        </ul>
        <p>Go <a href="{% url 'Catalog:catalog_page' %}">back</a></p>

    <hr><br/><br/>
        {% if product_per_page.has_previous %}
            <a href="?page=1"> &laquo First</a>
            <a href="?page={{product_per_page.previous_page_number}}">Previous</a>
        {% endif %}

        Page {{product_per_page.number}} of {{product_per_page.paginator.num_pages}}

        {% if product_per_page.has_next %}
            <a href="?page={{product_per_page.next_page_number}}">Next</a>
            <a href="?page={{product_per_page.paginator.num_pages}}">Last &raquo</a>
        {% endif %}

</html>

catalog/templates/Catalog/update_category.html
<html>
<h1> Update</h1>
    <form method = 'POST' enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{form.as_p}}</p>
        <input type="submit" value="Update">
    </form>
    <p><a href="{% url 'Catalog:catalog_page' %}">Back</a></p>
</html>

catalog/templates/Catalog/upload_category.html
<html>
<h1> Upload </h1>
    <form method = 'POST' enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{form.as_p}}</p>
        <button type="submit" >Submit</button>
    </form>
    <p><a href="{% url 'Catalog:catalog_page' %}">Back</a></p>
</html>

catalog/templates/Catalog/upload_form.html
<html>
<h1> Upload Book </h1>
    <form method = 'POST' enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{upload_form.as_p}}</p>
        <button type="submit" >Submit</button>
    </form>
</html>